In [1]:
import pandas as pd

In [76]:
network_data = pd.read_csv('Data/UNSW_NB15_training-set.csv',index_col='id')

In [77]:
network_data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
id,,,,,,,,,,,,,,,,,,,,,
1,0.000011,udp,-,INT,2,0,496,0,90909.0902,254,...,1,2,0,0,0,1,2,0,Normal,0
2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,254,...,1,2,0,0,0,1,2,0,Normal,0
3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,254,...,1,3,0,0,0,1,3,0,Normal,0
4,0.000006,udp,-,INT,2,0,900,0,166666.6608,254,...,1,3,0,0,0,2,3,0,Normal,0
5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,254,...,1,3,0,0,0,2,3,0,Normal,0

In [78]:
network_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 82332 entries, 1 to 82332
Data columns (total 44 columns):
dur                  82332 non-null float64
proto                82332 non-null object
service              82332 non-null object
state                82332 non-null object
spkts                82332 non-null int64
dpkts                82332 non-null int64
sbytes               82332 non-null int64
dbytes               82332 non-null int64
rate                 82332 non-null float64
sttl                 82332 non-null int64
dttl                 82332 non-null int64
sload                82332 non-null float64
dload                82332 non-null float64
sloss                82332 non-null int64
dloss                82332 non-null int64
sinpkt               82332 non-null float64
dinpkt               82332 non-null float64
sjit                 82332 non-null float64
djit                 82332 non-null float64
swin                 82332 non-null int64
stcpb                82332 non-null int64
dtcpb                82332 non-null int64
dwin                 82332 non-null int64
tcprtt               82332 non-null float64
synack               82332 non-null float64
ackdat               82332 non-null float64
smean                82332 non-null int64
dmean                82332 non-null int64
trans_depth          82332 non-null int64
response_body_len    82332 non-null int64
ct_srv_src           82332 non-null int64
ct_state_ttl         82332 non-null int64
ct_dst_ltm           82332 non-null int64
ct_src_dport_ltm     82332 non-null int64
ct_dst_sport_ltm     82332 non-null int64
ct_dst_src_ltm       82332 non-null int64
is_ftp_login         82332 non-null int64
ct_ftp_cmd           82332 non-null int64
ct_flw_http_mthd     82332 non-null int64
ct_src_ltm           82332 non-null int64
ct_srv_dst           82332 non-null int64
is_sm_ips_ports      82332 non-null int64
attack_cat           82332 non-null object
label                82332 non-null int64
dtypes: float64(11), int64(29), object(4)
memory usage: 28.3+ MB

In [79]:
from sklearn.preprocessing import LabelEncoder

In [80]:
cat_cols = ['proto','service','state']

In [81]:
for col in cat_cols:
    le = LabelEncoder()
    network_data[col] = le.fit_transform(network_data[col])

In [82]:
network_data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
id,,,,,,,,,,,,,,,,,,,,,
1,0.000011,117,0,4,2,0,496,0,90909.0902,254,...,1,2,0,0,0,1,2,0,Normal,0
2,0.000008,117,0,4,2,0,1762,0,125000.0003,254,...,1,2,0,0,0,1,2,0,Normal,0
3,0.000005,117,0,4,2,0,1068,0,200000.0051,254,...,1,3,0,0,0,1,3,0,Normal,0
4,0.000006,117,0,4,2,0,900,0,166666.6608,254,...,1,3,0,0,0,2,3,0,Normal,0
5,0.000010,117,0,4,2,0,2126,0,100000.0025,254,...,1,3,0,0,0,2,3,0,Normal,0

In [83]:
network_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 82332 entries, 1 to 82332
Data columns (total 44 columns):
dur                  82332 non-null float64
proto                82332 non-null int64
service              82332 non-null int64
state                82332 non-null int64
spkts                82332 non-null int64
dpkts                82332 non-null int64
sbytes               82332 non-null int64
dbytes               82332 non-null int64
rate                 82332 non-null float64
sttl                 82332 non-null int64
dttl                 82332 non-null int64
sload                82332 non-null float64
dload                82332 non-null float64
sloss                82332 non-null int64
dloss                82332 non-null int64
sinpkt               82332 non-null float64
dinpkt               82332 non-null float64
sjit                 82332 non-null float64
djit                 82332 non-null float64
swin                 82332 non-null int64
stcpb                82332 non-null int64
dtcpb                82332 non-null int64
dwin                 82332 non-null int64
tcprtt               82332 non-null float64
synack               82332 non-null float64
ackdat               82332 non-null float64
smean                82332 non-null int64
dmean                82332 non-null int64
trans_depth          82332 non-null int64
response_body_len    82332 non-null int64
ct_srv_src           82332 non-null int64
ct_state_ttl         82332 non-null int64
ct_dst_ltm           82332 non-null int64
ct_src_dport_ltm     82332 non-null int64
ct_dst_sport_ltm     82332 non-null int64
ct_dst_src_ltm       82332 non-null int64
is_ftp_login         82332 non-null int64
ct_ftp_cmd           82332 non-null int64
ct_flw_http_mthd     82332 non-null int64
ct_src_ltm           82332 non-null int64
ct_srv_dst           82332 non-null int64
is_sm_ips_ports      82332 non-null int64
attack_cat           82332 non-null object
label                82332 non-null int64
dtypes: float64(11), int64(32), object(1)
memory usage: 28.3+ MB

In [84]:
from sklearn.feature_selection import SelectKBest

In [93]:
select = SelectKBest(k=25)

In [94]:
network_tf = select.fit_transform(network_data.drop(['attack_cat'],axis=1),network_data.label)

C:\Users\awant\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw

In [95]:
network_tf[:5]

array([[0.00000000e+00, 4.00000000e+00, 9.09090902e+04, 2.54000000e+02,
        1.80363632e+08, 0.00000000e+00, 1.10000000e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00000000e+00,
        2.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        2.00000000e+00, 1.00000000e+00, 2.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 4.00000000e+00, 1.25000000e+05, 2.54000000e+02,
        8.81000000e+08, 0.00000000e+00, 8.00000000e-03, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00000000e+00,
        2.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        2.00000000e+00, 1.00000000e+00, 2.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 4.00000000e+00, 2.00000005e+05, 2.54000000e+02,
        8.54400000e+08, 0.00000000e+00, 5.00000000e-03, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.00000000e+00,
        2.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        3.00000000e+00, 1.00000000e+00, 3.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 4.00000000e+00, 1.66666661e+05, 2.54000000e+02,
        6.00000000e+08, 0.00000000e+00, 6.00000000e-03, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.00000000e+00,
        2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 1.00000000e+00,
        3.00000000e+00, 2.00000000e+00, 3.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 4.00000000e+00, 1.00000003e+05, 2.54000000e+02,
        8.50400000e+08, 0.00000000e+00, 1.00000000e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.00000000e+00,
        2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 1.00000000e+00,
        3.00000000e+00, 2.00000000e+00, 3.00000000e+00, 0.00000000e+00,
        0.00000000e+00]])

In [96]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [105]:
model_relu = Sequential()
model_relu.add(Dense(100, input_dim=25, activation='sigmoid')) 
# model_relu.add(Dense(50, activation='relu'))
# model_relu.add(Dense(25, activation='relu'))
model_relu.add(Dense(2, activation='softmax'))

In [106]:
model_relu.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [107]:
model_relu.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_23 (Dense)             (None, 100)               2600
_________________________________________________________________
dense_24 (Dense)             (None, 2)                 202
=================================================================
Total params: 2,802
Trainable params: 2,802
Non-trainable params: 0
_________________________________________________________________

In [108]:
from keras.utils import to_categorical

In [109]:
target = to_categorical(network_data.label)

In [110]:
target

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [111]:
model_relu.fit(network_tf, target,epochs=100,batch_size=20000)

Epoch 1/100
82332/82332 [==============================] - 1s 7us/step - loss: 0.8451 - acc: 0.5530
Epoch 2/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.6645 - acc: 0.6336
Epoch 3/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.6129 - acc: 0.6452
Epoch 4/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5910 - acc: 0.6520
Epoch 5/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5782 - acc: 0.6585
Epoch 6/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5677 - acc: 0.6659
Epoch 7/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5596 - acc: 0.6703
Epoch 8/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5534 - acc: 0.7237
Epoch 9/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5466 - acc: 0.7236
Epoch 10/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5408 - acc: 0.7341
Epoch 11/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5363 - acc: 0.7462
Epoch 12/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5314 - acc: 0.7521
Epoch 13/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5273 - acc: 0.7527
Epoch 14/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5237 - acc: 0.7525
Epoch 15/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5207 - acc: 0.7499
Epoch 16/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5184 - acc: 0.7491
Epoch 17/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5155 - acc: 0.7532
Epoch 18/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5136 - acc: 0.7540
Epoch 19/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5125 - acc: 0.7490
Epoch 20/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5106 - acc: 0.7535
Epoch 21/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.5093 - acc: 0.7540
Epoch 22/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.5083 - acc: 0.7541
Epoch 23/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.5079 - acc: 0.7531
Epoch 24/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.5067 - acc: 0.7543
Epoch 25/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.5056 - acc: 0.7542
Epoch 26/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5053 - acc: 0.7540
Epoch 27/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5053 - acc: 0.7542
Epoch 28/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5044 - acc: 0.7543
Epoch 29/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5043 - acc: 0.7546
Epoch 30/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5036 - acc: 0.7543
Epoch 31/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5036 - acc: 0.7533
Epoch 32/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5028 - acc: 0.7545
Epoch 33/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.5030 - acc: 0.7549
Epoch 34/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5025 - acc: 0.7552
Epoch 35/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5025 - acc: 0.7550
Epoch 36/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5027 - acc: 0.7543
Epoch 37/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5011 - acc: 0.7543
Epoch 38/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5009 - acc: 0.7544
Epoch 39/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.5009 - acc: 0.7544
Epoch 40/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.5006 - acc: 0.7543
Epoch 41/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5000 - acc: 0.7548
Epoch 42/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.5000 - acc: 0.7543
Epoch 43/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4988 - acc: 0.7549
Epoch 44/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.4986 - acc: 0.7544
Epoch 45/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.4985 - acc: 0.7544
Epoch 46/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4979 - acc: 0.7547
Epoch 47/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.4980 - acc: 0.7545
Epoch 48/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4969 - acc: 0.7544
Epoch 49/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4969 - acc: 0.7552
Epoch 50/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4971 - acc: 0.7550
Epoch 51/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4966 - acc: 0.7548
Epoch 52/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4970 - acc: 0.7542
Epoch 53/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4962 - acc: 0.7546
Epoch 54/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4965 - acc: 0.7551
Epoch 55/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4956 - acc: 0.7550
Epoch 56/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4970 - acc: 0.7559
Epoch 57/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4954 - acc: 0.7548
Epoch 58/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4957 - acc: 0.7556
Epoch 59/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4949 - acc: 0.7547
Epoch 60/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4947 - acc: 0.7546
Epoch 61/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4944 - acc: 0.7552
Epoch 62/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4947 - acc: 0.7553
Epoch 63/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4946 - acc: 0.7548
Epoch 64/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4944 - acc: 0.7550
Epoch 65/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4949 - acc: 0.7552
Epoch 66/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4945 - acc: 0.7547
Epoch 67/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4947 - acc: 0.7548
Epoch 68/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4950 - acc: 0.7547
Epoch 69/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.4947 - acc: 0.7554
Epoch 70/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4943 - acc: 0.7548
Epoch 71/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4942 - acc: 0.7551
Epoch 72/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4939 - acc: 0.7551
Epoch 73/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4942 - acc: 0.7561
Epoch 74/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4928 - acc: 0.7548
Epoch 75/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4936 - acc: 0.7552
Epoch 76/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4934 - acc: 0.7557
Epoch 77/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4924 - acc: 0.7560
Epoch 78/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4922 - acc: 0.7547
Epoch 79/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4920 - acc: 0.7557
Epoch 80/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4921 - acc: 0.7562
Epoch 81/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4926 - acc: 0.7551
Epoch 82/100

82332/82332 [==============================] - 0s 4us/step - loss: 0.4919 - acc: 0.7560
Epoch 83/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4921 - acc: 0.7558
Epoch 84/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4920 - acc: 0.7560
Epoch 85/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4923 - acc: 0.7554
Epoch 86/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4914 - acc: 0.7567
Epoch 87/100
82332/82332 [==============================] - 0s 5us/step - loss: 0.4911 - acc: 0.7558
Epoch 88/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4913 - acc: 0.7564
Epoch 89/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4905 - acc: 0.7562
Epoch 90/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4906 - acc: 0.7567
Epoch 91/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4904 - acc: 0.7554
Epoch 92/100
82332/82332 [==============================] - 0s 4us/step - loss: 0.4901 - acc: 0.7565
Epoch 93/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4905 - acc: 0.7557
Epoch 94/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4903 - acc: 0.7563
Epoch 95/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4902 - acc: 0.7566
Epoch 96/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4900 - acc: 0.7564
Epoch 97/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4899 - acc: 0.7565
Epoch 98/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4896 - acc: 0.7567
Epoch 99/100
82332/82332 [==============================] - 0s 3us/step - loss: 0.4893 - acc: 0.7562
Epoch 100/100
82332/82332 [==============================] - 1s 6us/step - loss: 0.4891 - acc: 0.7565